### PR TITLE
Improving the queries-based search for maps

### PR DESCRIPTION
**Pull request by matthew-ardi**

### CODE REVIEW

**Comment by matthew-ardi** [comment]
@waynewhbaaa is there any external library or source to handle multiple combinations of queries? it seemed tedious and unproductive to just have us hard code the combination

**Comment by waynewhbaaa** [comment]
> @waynewhbaaa is there any external library or source to handle multiple combinations of queries? it seemed tedious and unproductive to just have us hard code the combination

Sorry for replying late. I checked on online, and there are some links for iso-3166-2 codes packages might be useful:
http://www.ip2location.com/free/iso3166-2 in csv format, contains the code and also subdivision name. 
https://github.com/oodavid/iso-3166-2 contains geocode and codes for all subdivisions, but the data might be outdated.

I am currently looking through the camera.js again to see if there is a way to package multiple states and cities without additional information we get form fusiontable so far. I checked google map api about subdivison and google's defintion for subdivisions and cities are ambiguous.  See "Address Types and Address Component Types" section in this link: [https://developers.google.com/maps/documentation/javascript/geocoding](url)

By default the direct subdivisions that follow below any country is defined as "administrative_area_level_1" and below this is "administrative_area_level_2". If the places does have provinces/states/etc, administrative_area_level_1 will be provinces and states, and then administrative_area_level_2 will be city names. However, if the geocode locations only has the city names then there will be only administrative_area_level_1 indicating the cities. That means for all the indexes in the fusion table, formatting the queries request to country + subdivision names + cities into 3 search bars we got in our website might not work for google map request.

**Comment by matthew-ardi** [comment]
as we discussed before, we are ignoring the special cases of the queries-based search on the camera page.

**Comment by SionHu** [comment]
This branch will be closed tomorrow if

**Comment by SionHu** [comment]
This branch will be closed if not further agreement is achieved.

**Comment by matthew-ardi** [comment]
@waynewhbaaa is there any minor improvement that could be made other than the edge cases of the combination? otherwise, we can skip this pull request and just close it.

I am not aware of any

**Comment by waynewhbaaa** [comment]
@matthew-ardi Yeah I am not aware of it either, but if I could figure out I would reopen this for further discussion

**Pull request closed without merging**
